version: "3.7"

services:
  react_app:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
  recordings_api:
    build:
      context: ./recordings_api
      dockerfile: dev.Dockerfile
    # stdin_open: true
    # tty: true
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=0
    volumes:
      - ./recordings_api:/app
    ports:
      - "8001:8001"
    networks:
      - recordings
    depends_on:
      - recordings_db
  notes_api:
    build:
      context: ./notes_api
      dockerfile: dev.Dockerfile
    stdin_open: true
    tty: true
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=0
    volumes:
      - ./notes_api:/app
    ports:
      - "8002:8002"
    networks:
      - notes
    depends_on:
      - notes_db
  recordings_db:
    container_name: "recordings_db"
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recordings
      - POSTGRES_PASSWORD=teiath
    volumes:
      - "recordings_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - recordings
  notes_db:
    container_name: "notes_db"
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notes
      - POSTGRES_PASSWORD=teiath
    volumes:
      - "notes_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    networks:
      - notes
networks:
  recordings:
    driver: bridge
  notes:
    driver: bridge

volumes:
  recordings_data:
    driver: local
  notes_data:
    driver: local
