version: "3"

services:
  notes_db:
    container_name: "notes_db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notes
      - POSTGRES_PASSWORD=teiath
    volumes:
      - "notes_data:/var/lib/postgresql/data"
    ports:
      - "5433:5433"

volumes:
  notes_data:
    driver: local
