version: "3"

services:
  db:
    container_name: "recordings_db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recordings
      - POSTGRES_PASSWORD=teiath
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
