version: "3"

services:
  recordings_db:
    container_name: "recordings_db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recordings
      - POSTGRES_PASSWORD=teiath
    volumes:
      - "recordings_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  notes_db:
    container_name: "notes_db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notes
      - POSTGRES_PASSWORD=teiath
    volumes:
      - "notes_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"

volumes:
  notes_data:
    driver: local
  recordings_data:
    driver: local
